### ISSUE TITLE
Combiner optimization in Memory-conscious median and standard deviation example

### ISSUE THREAD

**Issue by zalacer** [adamjshook/mapreducepatterns#1]
In the code for the MedianStdDevCombiner class given on page 31 of the PDF version and in the source code donwloads, if count != null its value is updated but not used.  I think it should be used to update outValue and doing so affects the results.  The way I did this is with "outValue.put(entry.getKey(), count);"

**Comment by adamjshook** [comment]
Thank you for the comment!  In this code, count is stored in the outValue map as a LongWritable object.  When we fetch it from the map, if it is not null we update the value of 'count', which is still the same LongWritable object in the outValue map.  If it is null, we have not seen this key before so a new LongWritable object is created and set to the proper value.  Adding an additional call of outValue.put(entry.getKey(), count) in the 'not null' case would be more legible, but you are setting the key to the same LongWritable object.  It'll add some unnecessary processing, as the value has already been updated when we used count.set()

Does that make sense?

**Comment by zalacer** [comment]
Thanks for your reply!  I agree with your explanation and further testing
shows it works.  My mistake was not thinking sufficiently in terms of
objects and using the fact that every object is unique but can have
multiple references.  count is a reference for outValue.get(entry.getKey())
for the current entry so updating count updates what it references.
